source 'https://rubygems.org'
gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'monban'
gem 'monban-generators'
gem 'bourbon'
gem 'neat'
gem 'bitters'
gem 'dotenv-rails', group: :development
gem 'pusher'
gem 'carrierwave'
gem 'fog', "~> 1.3.1"
gem 'mini_magick'
